project: Milesto.xcodeproj
schemes:
  - Milesto
index_store_path:
  - ~/Library/Developer/Xcode/DerivedData/Milesto-ansltgdysfezzkauqkyjpqbljord/Index.noindex/DataStore
skip_build: true
retain_public: false
retain_objc_accessible: true
retain_codable_properties: true
disable_unused_import_analysis: false
report_exclude:
  - "Milesto/Sources/Shared/Icons/TablerIcons.swift"
