export const appConfig = {
  ai: {
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'google/gemini-3-flash-preview',
    callTimeoutMs: 30_000,
    embeddingModel: 'text-embedding-3-small',
    embeddingDimensions: 1536,
  },
  intake: {
    targetBatches: 5,
    maxBatches: 7,
    questionsPerBatch: { min: 3, max: 5 },
    maxProfileRetries: 3,
    qualityWarnThreshold: 0.5,
    model: 'google/gemini-3-flash-preview',
  },
  eval: {
    judgeModel: 'x-ai/grok-4.1-fast',
    judgeTemperature: 0,
    callTimeoutMs: 120_000,
  },
  throttle: {
    globalLimit: 60,
    globalTtlMs: 60_000,
    aiEndpointLimit: 10,
    aiEndpointTtlMs: 60_000,
  },
  roadmap: {
    matchCount: 20,
    matchThreshold: 0.7,
    rerankTopN: 10,
    milestoneModel: 'default',
    weeklyModel: 'default',
    dailyModel: 'default',
    maxGenerationAttempts: 3,
    generationTimeoutMs: 30_000,
    weeklyPlanTimeoutMs: 15_000,
    dailyObjectiveTimeoutMs: 10_000,
  },
  cohere: {
    apiVersion: '2',
    model: 'rerank-v3.5',
  },
  voice: {
    sttModel: 'gemini-2.5-flash',
    ttsModel: 'gemini-2.5-flash-preview-tts',
    liveModel: 'gemini-2.5-flash-native-audio-preview-12-2025',
    callTimeoutMs: 30_000,
    maxAudioSizeBytes: 10_485_760,
    supportedInputFormats: ['audio/wav', 'audio/mpeg', 'audio/mp4', 'audio/webm'],
    outputSampleRate: 24_000,
    sessionDurationMs: 840_000,
    sessionWarningMs: 780_000,
  },
  coach: {
    defaultCoachId: 1,
  },
  chat: {
    model: 'google/gemini-3-flash-preview',
    maxToolRounds: 5,
    maxHistoryMessages: 50,
    streamTimeoutMs: 60_000,
    searchMatchCount: 10,
    searchMatchThreshold: 0.5,
    searchResultCount: 5,
    insightDuplicateThreshold: 0.92,
    insightDuplicateCheckCount: 5,
  },
};
